//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UStoreMVC.Data.EF
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int ProductID { get; set; }
        public string Name { get; set; }
        public string Description { get; set; }
        public Nullable<decimal> Price { get; set; }
        public short UnitsInStock { get; set; }
        public string ProductImage { get; set; }
        public int StatusID { get; set; }
        public Nullable<int> CategoryID { get; set; }
        public string Notes { get; set; }
        public string ReferenceURL { get; set; }
    
        public virtual Category Category { get; set; }
        public virtual Status Status { get; set; }
    }
}
